spring:
    application:
        name: log
server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8089/eureka}
    instance:
        preferIpAddress: true